export const colors = {
  primary: 'var(--color-primary)',
  'primary-light': 'var(--color-primary-light)',
  'primary-dark': 'var(--color-primary-dark)',
  secondary: 'var(--color-secondary)',
  'secondary-light': 'var(--color-secondary-light)',
  'secondary-dark': 'var(--color-secondary-dark)',
  accent: 'var(--color-accent)',
  'accent-soft': 'var(--color-accent-soft)',
  'soft-feminine': 'var(--color-soft-feminine)',
  bg: 'var(--color-bg)',
  surface: 'var(--color-surface)',
  'surface-tint': 'var(--color-surface-tint)',
  'text-primary': 'var(--color-text-primary)',
  'text-secondary': 'var(--color-text-secondary)',
  'text-inverse': 'var(--color-text-inverse)',
  border: 'var(--color-border)',
  'border-focus': 'var(--color-border-focus)',
  success: 'var(--color-success)',
  warning: 'var(--color-warning)',
  error: 'var(--color-error)',
} as const;